version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    volumes:
      - application-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command:
      - postgres
      - -c
      - shared_buffers=128MB
      - -c
      - effective_cache_size=256MB
      - -c
      - max_connections=100
      - -c
      - log_statement=all
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d myapp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  application-db:
    driver: local