postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: alphauser
  PostgresqlDbName: backend
  PostgresqlSharedBuffers: 128MB
  PostgresqlEffectiveCacheSize: 256MB
  PostgresqlMaxConnections: 100
  PostgresqlSslMode: disable
  Pgdriver: pg


